### PR TITLE
official_devices: Welcome X00TD to the warzone

### PR DESCRIPTION
**Pull request by sarthakroy2002**
Signed-off-by: Sarthak Roy <sarthakroy2002@gmail.com>
Change-Id: I606114230ef426c6b1b1fe39e00533af0e191d69

### CODE REVIEW

**Comment by SakthivelNadar** [comment]
@sarthakroy2002 Ok

**Comment by cyberknight777** [comment]
@SakthivelNadar Ok

**Comment by sajidshahriar72543** [comment]
@cyberknight777 ok

**Review by whyredfire — APPROVED** [review]

**Comment by kawaaii** [comment]
Ok

**Pull request merged**
