### PR TITLE
API/Devices: Welcome peridot device

### PR DESCRIPTION
**Pull request by raghavt20**

### CODE REVIEW

**Review by whyredfire — APPROVED** [review]

**Comment by dasshubham762** [comment]
Pru gawd @raghavt20 here

**Comment by ondrejnedoma** [comment]
Any ETA when the first official build is gonna come out?

**Comment by kawaaii** [comment]
> Any ETA when the first official build is gonna come out?

No

**Comment by wangpingfan** [comment]
Hi,@raghavt20 Please insert the installation instructions at https://pixelos.net/download/peridot. THS.

**Pull request merged**
